import { Dashboard as DashboardPage } from './dashboard/Dashboard';
import { Clients as ClientsPage } from './clients/Clients';
import { Create as CreateClientPage } from './clients/Create';
import { Edit as EditClientPage } from './clients/Edit';
import { Languages as LanguagesPage } from './dictionaries/common/Languages';
import { Countries as CountriesPage } from './dictionaries/common/Countries';
import { Currencies as CurrenciesPage } from './dictionaries/common/Currencies';
import { ClientTypes as ClientTypesPage } from './dictionaries/client/ClientTypes';
import { Account as AccountPage } from './account/Account';
import { Create as CreateClientTypePage } from './dictionaries/client/Create';
import { Edit as EditClientTypePage } from './dictionaries/client/Edit';

export const Dashboard = DashboardPage;
export const Clients = ClientsPage;
export const CreateClient = CreateClientPage;
export const EditClient = EditClientPage;
export const Languages = LanguagesPage;
export const Countries = CountriesPage;
export const Currencies = CurrenciesPage;
export const ClientTypes = ClientTypesPage;
export const CreateClientType = CreateClientTypePage;
export const EditClientType = EditClientTypePage;
export const Account = AccountPage;
